# Area names are hw_nest, hw_arsenal, hw_streets, hw_lighthouse, hw_lakeside, hw_sanct, hw_depths, hw_aurum
# areas:
#   0: "hw_lighthouse"
#   1: "hw_arsenal"
#   2: "hw_streets"
#   ordered: false # Whether areas should appear in the order specified

ranges:
  chest_ranges:
     # - start: 0  # Chest index (0 = Chest 1)
     #   end: 1    # Chest index (1 = Chest 2)
     #   required_items: []  # Items that must appear somewhere in this range
     #   unique: false  # If true, each item must be in a different chest
     # Example: Mountain Staff and Firststrike Bracelet in first 2 chests, different chests
     # - start: 0
     #   end: 0
     #   required_items: ["Obsidian Rod"]
     - start: 0
       end: 5
       # required_items: ["Royal Staff", "Spark of Determination", "Mermaid Scalemail", "Pajama Hat", "Crowfeather Hairpin", "Ivy Staff"] # 73389
       # required_items: ["Lullaby Harp","Eternity Flute","Waterfall Polearm","Sacred Bow","Blue Rose","Sniper's Eyeglasses"]
       required_items: ["Obsidian Hairpin","Nightingale Gown","Icicle Earrings","Saltwater Staff","Strawberry Cake","Stoneplate Armor"] # 47821
     # - start: 0
     #   end: 3
     #   required_items: ["Venom Hood", "Blood Vial", "Rainbow Cape", "Youkai Bracelet"]
     #   unique: true
  
  # shop_ranges:
     # - start: 0  # Shop index (0 = Shop 1)
     #   end: 0    
     #   required_upgrades: []  # Upgrades that must appear somewhere in this range
     #   unique: false  # If true, each upgrade must be in a different shop
     #   max_cost: null  # Maximum cost for required upgrades (null = any cost)
     # Example: g2 e3 affordable in first shop
     # - start: 0
     #   end: 0
     #   required_upgrades: ["Garnet Secondary Upgrade", "Emerald Special Upgrade"]
     #   unique: false
     #   max_cost: 24
     # - start: 0
     #   end: 0
     #   required_upgrades: ["Emerald Special Upgrade"]
     #   unique: false
     #   max_cost: null
