pub fn get_area_name(area_index: usize) -> Option<&'static str> {
    AREA_NAMES.get(area_index).map(|&out| out)
}

pub fn get_area_name_pretty(area_index: usize) -> Option<&'static str> {
    match area_index {
        1 => Some("Scholar's Nest"),
        2 => Some("King's Arsenal"),
        3 => Some("Red Darkhouse"),
        4 => Some("Churchmouse Streets"),
        5 => Some("Emerald Lakeside"),
        // 6 => Some("The Pale Keep"),
        _ => get_area_name(area_index),
    }
}

pub fn get_pale_keep_name_pretty(area_index: usize) -> Option<&'static str> {
    match area_index {
        0 => Some("Staff"),
        1 => Some("Knives"),
        2 => Some("Axe"),
        3 => Some("Spear & Shield"),
        4 => Some("Harp"),
        _ => None,
    }
}

pub fn get_outskirt_name(fight_index: usize, pattern: usize) -> Option<&'static str> {
    OUTSKIRT_NAMES
        .get(fight_index)
        .map(|patterns| patterns.get(pattern))
        .flatten()
        .map(|&out| out)
}

pub fn get_pale_keep_name(pale_keep_index: usize) -> Option<&'static str> {
    PALE_KEEP_NAMES.get(pale_keep_index).map(|&out| out)
}

pub fn get_item_name(item_index: usize) -> Option<&'static str> {
    OBJECT_NAMES.get(item_index).map(|&out| out)
}

pub fn get_encounter_name(encounter_index: usize) -> Option<&'static str> {
    ENCOUNTER_NAMES.get(encounter_index).map(|&out| out)
}

const AREA_NAMES: [&'static str; 12] = [
    "hw_outskirts",
    "hw_nest",
    "hw_arsenal",
    "hw_lighthouse",
    "hw_streets",
    "hw_lakeside",
    "hw_keep",
    "hw_geode",
    "hw_sanct",
    "hw_depths",
    "hw_aurum",
    "hw_darkhall",
];

const OUTSKIRT_NAMES: [[&'static str; 2]; 5] = [
    ["enc_bird_sophomore1", "enc_bird_sophomore2"],
    ["enc_frog_tinkerer1", "enc_frog_tinkerer2"],
    ["enc_dragon_granite1", "enc_dragon_granite2"],
    ["enc_wolf_blackear1", "enc_wolf_blackear2"],
    ["enc_mouse_cadet1", "enc_mouse_cadet2"],
];

const PALE_KEEP_NAMES: [&'static str; 5] = [
    "enc_queens_staff0",
    "enc_queens_knife0",
    "enc_queens_axe0",
    "enc_queens_spear0",
    "enc_queens_harp0",
];

const OBJECT_NAMES: [&'static str; 716] = [
    "nothing_item",
    "???",
    "???",
    "???",
    "???",
    "???",
    "Dimi Moonburst",
    "Diamond Dimi Moonburst",
    "Opal Dimi Moonburst",
    "Sapphire Dimi Moonburst",
    "Ruby Dimi Moonburst",
    "Garnet Dimi Moonburst",
    "Emerald Dimi Moonburst",
    "Lat Moonburst",
    "Diamond Lat Moonburst",
    "Opal Lat Moonburst",
    "Sapphire Lat Moonburst",
    "Ruby Lat Moonburst",
    "Garnet Lat Moonburst",
    "Emerald Lat Moonburst",
    "Astral Swirl",
    "Diamond Astral Swirl",
    "Opal Astral Swirl",
    "Sapphire Astral Swirl",
    "Ruby Astral Swirl",
    "Garnet Astral Swirl",
    "Emerald Astral Swirl",
    "Astral Seal",
    "Diamond Astral Seal",
    "Opal Astral Seal",
    "Sapphire Astral Seal",
    "Ruby Astral Seal",
    "Garnet Astral Seal",
    "Emerald Astral Seal",
    "Swift Cut",
    "Diamond Swift Cut",
    "Opal Swift Cut",
    "Sapphire Swift Cut",
    "Ruby Swift Cut",
    "Garnet Swift Cut",
    "Emerald Swift Cut",
    "Knife Juggle",
    "Diamond Knife Juggle",
    "Opal Knife Juggle",
    "Sapphire Knife Juggle",
    "Ruby Knife Juggle",
    "Garnet Knife Juggle",
    "Emerald Knife Juggle",
    "Assassinate",
    "Diamond Assassinate",
    "Opal Assassinate",
    "Sapphire Assassinate",
    "Ruby Assassinate",
    "Garnet Assassinate",
    "Emerald Assassinate",
    "Shadowstep",
    "Diamond Shadowstep",
    "Opal Shadowstep",
    "Sapphire Shadowstep",
    "Ruby Shadowstep",
    "Garnet Shadowstep",
    "Emerald Shadowstep",
    "Full Moon",
    "Diamond Full Moon",
    "Opal Full Moon",
    "Sapphire Full Moon",
    "Ruby Full Moon",
    "Garnet Full Moon",
    "Emerald Full Moon",
    "Dark Wave",
    "Diamond Dark Wave",
    "Opal Dark Wave",
    "Sapphire Dark Wave",
    "Ruby Dark Wave",
    "Garnet Dark Wave",
    "Emerald Dark Wave",
    "Spinning Leap",
    "Diamond Spinning Leap",
    "Opal Spinning Leap",
    "Sapphire Spinning Leap",
    "Ruby Spinning Leap",
    "Garnet Spinning Leap",
    "Emerald Spinning Leap",
    "Shadow Barrier",
    "Diamond Shadow Barrier",
    "Opal Shadow Barrier",
    "Sapphire Shadow Barrier",
    "Ruby Shadow Barrier",
    "Garnet Shadow Barrier",
    "Emerald Shadow Barrier",
    "Twirling Rose",
    "Diamond Twirling Rose",
    "Opal Twirling Rose",
    "Sapphire Twirling Rose",
    "Ruby Twirling Rose",
    "Garnet Twirling Rose",
    "Emerald Twirling Rose",
    "Falling Petal",
    "Diamond Falling Petal",
    "Opal Falling Petal",
    "Sapphire Falling Petal",
    "Ruby Falling Petal",
    "Garnet Falling Petal",
    "Emerald Falling Petal",
    "Lily Blossom",
    "Diamond Lily Blossom",
    "Opal Lily Blossom",
    "Sapphire Lily Blossom",
    "Ruby Lily Blossom",
    "Garnet Lily Blossom",
    "Emerald Lily Blossom",
    "Golden Grace",
    "Diamond Golden Grace",
    "Opal Golden Grace",
    "Sapphire Golden Grace",
    "Ruby Golden Grace",
    "Garnet Golden Grace",
    "Emerald Golden Grace",
    "Dimi Life",
    "Diamond Dimi Life",
    "Opal Dimi Life",
    "Sapphire Dimi Life",
    "Ruby Dimi Life",
    "Garnet Dimi Life",
    "Emerald Dimi Life",
    "Lat Life",
    "Diamond Lat Life",
    "Opal Lat Life",
    "Sapphire Lat Life",
    "Ruby Lat Life",
    "Garnet Lat Life",
    "Emerald Lat Life",
    "Summon Spirit",
    "Diamond Summon Spirit",
    "Opal Summon Spirit",
    "Sapphire Summon Spirit",
    "Ruby Summon Spirit",
    "Garnet Summon Spirit",
    "Emerald Summon Spirit",
    "Nature's Blessing",
    "Diamond Nature's Blessing",
    "Opal Nature's Blessing",
    "Sapphire Nature's Blessing",
    "Ruby Nature's Blessing",
    "Garnet Nature's Blessing",
    "Emerald Nature's Blessing",
    "Sword Thrust",
    "Diamond Sword Thrust",
    "Opal Sword Thrust",
    "Sapphire Sword Thrust",
    "Ruby Sword Thrust",
    "Garnet Sword Thrust",
    "Emerald Sword Thrust",
    "Siphon Spell",
    "Diamond Siphon Spell",
    "Opal Siphon Spell",
    "Sapphire Siphon Spell",
    "Ruby Siphon Spell",
    "Garnet Siphon Spell",
    "Emerald Siphon Spell",
    "Magicked Fleche",
    "Diamond Magicked Fleche",
    "Opal Magicked Fleche",
    "Sapphire Magicked Fleche",
    "Ruby Magicked Fleche",
    "Garnet Magicked Fleche",
    "Emerald Magicked Fleche",
    "Novi Dark",
    "Diamond Novi Dark",
    "Opal Novi Dark",
    "Sapphire Novi Dark",
    "Ruby Novi Dark",
    "Garnet Novi Dark",
    "Emerald Novi Dark",
    "Arrowshot",
    "Diamond Arrowshot",
    "Opal Arrowshot",
    "Sapphire Arrowshot",
    "Ruby Arrowshot",
    "Garnet Arrowshot",
    "Emerald Arrowshot",
    "Rabbitsnare",
    "Diamond Rabbitsnare",
    "Opal Rabbitsnare",
    "Sapphire Rabbitsnare",
    "Ruby Rabbitsnare",
    "Garnet Rabbitsnare",
    "Emerald Rabbitsnare",
    "Barrage",
    "Diamond Barrage",
    "Opal Barrage",
    "Sapphire Barrage",
    "Ruby Barrage",
    "Garnet Barrage",
    "Emerald Barrage",
    "Careful Aim",
    "Diamond Careful Aim",
    "Opal Careful Aim",
    "Sapphire Careful Aim",
    "Ruby Careful Aim",
    "Garnet Careful Aim",
    "Emerald Careful Aim",
    "Flame Hook",
    "Diamond Flame Hook",
    "Opal Flame Hook",
    "Sapphire Flame Hook",
    "Ruby Flame Hook",
    "Garnet Flame Hook",
    "Emerald Flame Hook",
    "Quick Jab",
    "Diamond Quick Jab",
    "Opal Quick Jab",
    "Sapphire Quick Jab",
    "Ruby Quick Jab",
    "Garnet Quick Jab",
    "Emerald Quick Jab",
    "Fury",
    "Diamond Fury",
    "Opal Fury",
    "Sapphire Fury",
    "Ruby Fury",
    "Garnet Fury",
    "Emerald Fury",
    "Footwork",
    "Diamond Footwork",
    "Opal Footwork",
    "Sapphire Footwork",
    "Ruby Footwork",
    "Garnet Footwork",
    "Emerald Footwork",
    "Spear Thrust",
    "Diamond Spear Thrust",
    "Opal Spear Thrust",
    "Sapphire Spear Thrust",
    "Ruby Spear Thrust",
    "Garnet Spear Thrust",
    "Emerald Spear Thrust",
    "Lat Holy",
    "Diamond Lat Holy",
    "Opal Lat Holy",
    "Sapphire Lat Holy",
    "Ruby Lat Holy",
    "Garnet Lat Holy",
    "Emerald Lat Holy",
    "Novi Holy",
    "Diamond Novi Holy",
    "Opal Novi Holy",
    "Sapphire Novi Holy",
    "Ruby Novi Holy",
    "Garnet Novi Holy",
    "Emerald Novi Holy",
    "Roll & Phalanx",
    "Diamond Roll & Phalanx",
    "Opal Roll & Phalanx",
    "Sapphire Roll & Phalanx",
    "Ruby Roll & Phalanx",
    "Garnet Roll & Phalanx",
    "Emerald Roll & Phalanx",
    "Strike Command",
    "Diamond Strike Command",
    "Opal Strike Command",
    "Sapphire Strike Command",
    "Ruby Strike Command",
    "Garnet Strike Command",
    "Emerald Strike Command",
    "March Command",
    "Diamond March Command",
    "Opal March Command",
    "Sapphire March Command",
    "Ruby March Command",
    "Garnet March Command",
    "Emerald March Command",
    "Abyssal Call",
    "Diamond Abyssal Call",
    "Opal Abyssal Call",
    "Sapphire Abyssal Call",
    "Ruby Abyssal Call",
    "Garnet Abyssal Call",
    "Emerald Abyssal Call",
    "Protect Command",
    "Diamond Protect Command",
    "Opal Protect Command",
    "Sapphire Protect Command",
    "Ruby Protect Command",
    "Garnet Protect Command",
    "Emerald Protect Command",
    "Rabbitsmash",
    "Diamond Rabbitsmash",
    "Opal Rabbitsmash",
    "Sapphire Rabbitsmash",
    "Ruby Rabbitsmash",
    "Garnet Rabbitsmash",
    "Emerald Rabbitsmash",
    "Step & Swing",
    "Diamond Step & Swing",
    "Opal Step & Swing",
    "Sapphire Step & Swing",
    "Ruby Step & Swing",
    "Garnet Step & Swing",
    "Emerald Step & Swing",
    "Doublesmash",
    "Diamond Doublesmash",
    "Opal Doublesmash",
    "Sapphire Doublesmash",
    "Ruby Doublesmash",
    "Garnet Doublesmash",
    "Emerald Doublesmash",
    "Wheel Swing",
    "Diamond Wheel Swing",
    "Opal Wheel Swing",
    "Sapphire Wheel Swing",
    "Ruby Wheel Swing",
    "Garnet Wheel Swing",
    "Emerald Wheel Swing",
    "Dimi Fire",
    "Diamond Dimi Fire",
    "Opal Dimi Fire",
    "Sapphire Dimi Fire",
    "Ruby Dimi Fire",
    "Garnet Dimi Fire",
    "Emerald Dimi Fire",
    "Lat Fire",
    "Diamond Lat Fire",
    "Opal Lat Fire",
    "Sapphire Lat Fire",
    "Ruby Lat Fire",
    "Garnet Lat Fire",
    "Emerald Lat Fire",
    "Flare Kick",
    "Diamond Flare Kick",
    "Opal Flare Kick",
    "Sapphire Flare Kick",
    "Ruby Flare Kick",
    "Garnet Flare Kick",
    "Emerald Flare Kick",
    "Smokestep",
    "Diamond Smokestep",
    "Opal Smokestep",
    "Sapphire Smokestep",
    "Ruby Smokestep",
    "Garnet Smokestep",
    "Emerald Smokestep",
    "Pistolshot",
    "Diamond Pistolshot",
    "Opal Pistolshot",
    "Sapphire Pistolshot",
    "Ruby Pistolshot",
    "Garnet Pistolshot",
    "Emerald Pistolshot",
    "Reload",
    "Diamond Reload",
    "Opal Reload",
    "Sapphire Reload",
    "Ruby Reload",
    "Garnet Reload",
    "Emerald Reload",
    "Mixed Bomb",
    "Diamond Mixed Bomb",
    "Opal Mixed Bomb",
    "Sapphire Mixed Bomb",
    "Ruby Mixed Bomb",
    "Garnet Mixed Bomb",
    "Emerald Mixed Bomb",
    "Take Cover",
    "Diamond Take Cover",
    "Opal Take Cover",
    "Sapphire Take Cover",
    "Ruby Take Cover",
    "Garnet Take Cover",
    "Emerald Take Cover",
    "Anger",
    "Diamond Anger",
    "Opal Anger",
    "Sapphire Anger",
    "Ruby Anger",
    "Garnet Anger",
    "Emerald Anger",
    "Envy",
    "Diamond Envy",
    "Opal Envy",
    "Sapphire Envy",
    "Ruby Envy",
    "Garnet Envy",
    "Emerald Envy",
    "Sadness",
    "Diamond Sadness",
    "Opal Sadness",
    "Sapphire Sadness",
    "Ruby Sadness",
    "Garnet Sadness",
    "Emerald Sadness",
    "Panic",
    "Diamond Panic",
    "Opal Panic",
    "Sapphire Panic",
    "Ruby Panic",
    "Garnet Panic",
    "Emerald Panic",
    "???",
    "Raven Grimoire",
    "Blackwing Staff",
    "Curse Talon",
    "Darkmagic Blade",
    "Witch's Cloak",
    "Crowfeather Hairpin",
    "Redblack Ribbon",
    "Opal Necklace",
    "Sleeping Greatbow",
    "Crescentmoon Dagger",
    "Lullaby Harp",
    "Nightstar Grimoire",
    "Moon Pendant",
    "Pajama Hat",
    "Stuffed Rabbit",
    "Nightingale Gown",
    "Eternity Flute",
    "Timewarp Wand",
    "Chrome Shield",
    "Clockwork Tome",
    "Metronome Boots",
    "Timemage Cap",
    "Starry Cloak",
    "Gemini Necklace",
    "Hawkfeather Fan",
    "Windbite Dagger",
    "Pidgeon Bow",
    "Shinsoku Katana",
    "Eaglewing Charm",
    "Sparrow Feather",
    "Winged Cap",
    "Thief's Coat",
    "Vampiric Dagger",
    "Bloody Bandage",
    "Leech Staff",
    "Bloodhound Greatsword",
    "Reaper Cloak",
    "Bloodflower Brooch",
    "Wolf Hood",
    "Blood Vial",
    "Black Wakizashi",
    "Throwing Dagger",
    "Assassin's Knife",
    "Ninjutsu Scroll",
    "Shadow Bracelet",
    "Ninja Robe",
    "Kunoichi Hood",
    "Shinobi Tabi",
    "Dragonhead Spear",
    "Granite Greatsword",
    "Greysteel Shield",
    "Stonebreaker Staff",
    "Tough Gauntlet",
    "Rockdragon Mail",
    "Obsidian Hairpin",
    "Iron Greaves",
    "Volcano Spear",
    "Reddragon Blade",
    "Flame Bow",
    "Meteor Staff",
    "Phoenix Charm",
    "Firescale Corset",
    "Demon Horns",
    "Flamewalker Boots",
    "Diamond Shield",
    "Peridot Rapier",
    "Garnet Staff",
    "Sapphire Violin",
    "Emerald Chestplate",
    "Amethyst Bracelet",
    "Topaz Charm",
    "Ruby Circlet",
    "Brightstorm Spear",
    "Bolt Staff",
    "Lightning Bow",
    "Darkstorm Knife",
    "Darkcloud Necklace",
    "Crown of Storms",
    "Thunderclap Gloves",
    "Storm Petticoat",
    "Holy Greatsword",
    "Sacred Bow",
    "Purification Rod",
    "Ornamental Bell",
    "Shrinemaiden's Kosode",
    "Redwhite Ribbon",
    "Divine Mirror",
    "Golden Chime",
    "Book of Cheats",
    "Golden Katana",
    "Glittering Trumpet",
    "Royal Staff",
    "Ballroom Gown",
    "Silver Coin",
    "Queen's Crown",
    "Mimick Rabbitfoot",
    "Butterfly Ocarina",
    "Fairy Spear",
    "Moss Shield",
    "Floral Bow",
    "Blue Rose",
    "Sunflower Crown",
    "Midsummer Dress",
    "Grasswoven Bracelet",
    "Snakefang Dagger",
    "Ivy Staff",
    "Deathcap Tome",
    "Spiderbite Bow",
    "Compound Gloves",
    "Poisonfrog Charm",
    "Venom Hood",
    "Chemist's Coat",
    "Seashell Shield",
    "Necronomicon",
    "Tidal Greatsword",
    "Occult Dagger",
    "Mermaid Scalemail",
    "Hydrous Blob",
    "Abyss Artifact",
    "Lost Pendant",
    "Sawtooth Cleaver",
    "Raven's Dagger",
    "Killing Note",
    "Blacksteel Buckler",
    "Nightguard Gloves",
    "Sniper's Eyeglasses",
    "Darkmage Charm",
    "Firststrike Bracelet",
    "Obsidian Rod",
    "Darkglass Spear",
    "Timespace Dagger",
    "Quartz Shield",
    "Pocketwatch",
    "Nova Crown",
    "Blackhole Charm",
    "Twinstar Earrings",
    "Kyou No Omikuji",
    "Youkai Bracelet",
    "Oni Staff",
    "Kappa Shield",
    "Usagi Kamen",
    "Red Tanzaku",
    "Vega Spear",
    "Altair Dagger",
    "Ghost Spear",
    "Phantom Dagger",
    "Cursed Candlestaff",
    "Haunted Gloves",
    "Old Bonnet",
    "Maid Outfit",
    "Calling Bell",
    "Smoke Shield",
    "Grandmaster Spear",
    "Teacher Knife",
    "Tactician Rod",
    "Spiked Shield",
    "Battlemaiden Armor",
    "Gladiator Helmet",
    "Lancer Gauntlets",
    "Lion Charm",
    "Bluebolt Staff",
    "Lapis Sword",
    "Shockwave Tome",
    "Battery Shield",
    "Raiju Crown",
    "Staticshock Earrings",
    "Stormdance Gown",
    "Blackbolt Ribbon",
    "Crane Katana",
    "Falconfeather Dagger",
    "Tornado Staff",
    "Cloud Guard",
    "Hermes Bow",
    "Talon Charm",
    "Tiny Wings",
    "Feathered Overcoat",
    "Sandpriestess Spear",
    "Flamedancer Dagger",
    "Whiteflame Staff",
    "Sacred Shield",
    "Marble Clasp",
    "Sun Pendant",
    "Tiny Hourglass",
    "Desert Earrings",
    "Giant Stone Club",
    "Ruins Sword",
    "Mountain Staff",
    "Boulder Shield",
    "Golem's Claymore",
    "Stoneplate Armor",
    "Sacredstone Charm",
    "Clay Rabbit",
    "Waterfall Polearm",
    "Vorpal Dao",
    "Jade Staff",
    "Reflection Shield",
    "Butterfly Hairpin",
    "Watermage Pendant",
    "Raindrop Earrings",
    "Aquamarine Bracelet",
    "Glacier Spear",
    "Frost Dagger",
    "Frozen Staff",
    "Coldsteel Shield",
    "Polar Coat",
    "Icicle Earrings",
    "Winter Hat",
    "Snow Boots",
    "Spear of Remorse",
    "Memory Greatsword",
    "Staff of Sorrow",
    "Shield of Smiles",
    "Lonesome Pendant",
    "Spark of Determination",
    "Crown of Love",
    "Comforting Coat",
    "Righthand Cast",
    "Lefthand Cast",
    "Hexed Blindfold",
    "Angel's Halo",
    "Unsacred Pendant",
    "Whitewing Bracelet",
    "Darkcrystal Rose",
    "Dark Wings",
    "Giant Paintbrush",
    "Sewing Sword",
    "Sketchbook",
    "Palette Shield",
    "Handmade Charm",
    "Painter's Beret",
    "Artist Smock",
    "Colorful Earrings",
    "Daylight Sword",
    "Nightgleam Sword",
    "Spear of Winds",
    "Spear of Rains",
    "Heaven's Codex",
    "Hell's Codex",
    "Robe of Light",
    "Robe of Dark",
    "Hooked Staff",
    "Springloaded Scythe",
    "Hidden Blade",
    "Sharpedged Shield",
    "Pointed Ring",
    "Crown of Swords",
    "Bladed Cloak",
    "Greatsword Pendant",
    "Rusted Greatsword",
    "Sand Shovel",
    "Saltwater Staff",
    "Large Umbrella",
    "Onepiece Swimsuit",
    "Straw Hat",
    "Large Anchor",
    "Beach Sandals",
    "Strongman's Bar",
    "Spinning Chakram",
    "Ribboned Staff",
    "Trick Shield",
    "Rosered Leotard",
    "Jester's Hat",
    "Rainbow Cape",
    "Performer's Shoes",
    "Iron Pickaxe",
    "Dynamite Staff",
    "Fossil Dagger",
    "Drill Shield",
    "Canary Charm",
    "Pyrite Earrings",
    "Caver's Cloak",
    "Miner's Headlamp",
    "Tiny Fork",
    "Stirring Spoon",
    "Fanciful Book",
    "Apple Plate",
    "Vanilla Wafers",
    "Caramel Tea",
    "Strawberry Cake",
    "Sweet Taffy",
    "Full Heal",
    "Level Up",
    "Regeneration Potion",
    "Essence of Spell",
    "Darkness Potion",
    "Quickening Potion",
    "Winged Potion",
    "Essence of Wit",
    "Swifthand Potion",
    "Fire Potion",
    "Essence of Strength",
    "Golden Potion",
    "Luck Potion",
    "Essence of Steel",
    "Evasion Potion",
    "Longarm Potion",
    "Vitality Potion",
    "Opal Primary Upgrade",
    "Opal Secondary Upgrade",
    "Opal Special Upgrade",
    "Opal Defensive Upgrade",
    "Sapphire Primary Upgrade",
    "Sapphire Secondary Upgrade",
    "Sapphire Special Upgrade",
    "Sapphire Defensive Upgrade",
    "Ruby Primary Upgrade",
    "Ruby Secondary Upgrade",
    "Ruby Special Upgrade",
    "Ruby Defensive Upgrade",
    "Garnet Primary Upgrade",
    "Garnet Secondary Upgrade",
    "Garnet Special Upgrade",
    "Garnet Defensive Upgrade",
    "Emerald Primary Upgrade",
    "Emerald Secondary Upgrade",
    "Emerald Special Upgrade",
    "Emerald Defensive Upgrade",
];

const ENCOUNTER_NAMES: [&'static str; 158] = [
    "enc_training_nothing",
    "enc_training_circles",
    "enc_training_circle_spreads",
    "enc_training_cones",
    "enc_training_cone_spreads",
    "enc_training_line",
    "enc_training_line_spreads",
    "enc_training_prscircle",
    "enc_training_linestack",
    "enc_training_linestack_follow",
    "enc_training_spinray",
    "enc_training_spinfast",
    "enc_training_enlarge_bullet",
    "enc_training_enlarge_ray",
    "enc_training_colormatch",
    "enc_training_clockspot",
    "enc_training_cardinal",
    "enc_training_cleave",
    "enc_training_tether",
    "enc_training_tether_fixed",
    "enc_training_movecheck",
    "enc_training_thorns",
    "enc_training_thorns_fixed",
    "enc_training_marching",
    "enc_training_bind",
    "enc_training_gravity",
    "enc_training_heavy",
    "enc_training_tailwind",
    "enc_training_teleport",
    "enc_training_timestop",
    "enc_training_fieldlimit",
    "enc_training_fieldlimit2",
    "enc_training_displayorder",
    "enc_training_enrage",
    "enc_training_transform",
    "enc_training_transform_minor",
    "enc_training_dark0",
    "enc_training_dark1",
    "enc_training_dark2",
    "enc_training_steel0",
    "enc_training_steel1",
    "enc_training_fire0",
    "enc_training_fire1",
    "enc_training_light0",
    "enc_training_light1",
    "enc_training_water0",
    "enc_training_water1",
    "enc_training_spinning_cardinal",
    "enc_training_angel_circle",
    "enc_training_deathwall",
    "enc_training_target_tether",
    "enc_training_summon_butterfly",
    "enc_training_summon_fishpool",
    "enc_training_summon_jellycat",
    "enc_training_bloom_ring",
    "enc_training_blackwhite_spawn",
    "enc_training_playermirror",
    "enc_training_summon_aurumsword",
    "enc_training_gem_pick",
    "enc_training_angel_appear",
    "enc_training_pattern_erase",
    "enc_bird_sophomore0",
    "enc_bird_sophomore1",
    "enc_bird_sophomore2",
    "enc_wolf_blackear0",
    "enc_wolf_blackear1",
    "enc_wolf_blackear2",
    "enc_dragon_granite0",
    "enc_dragon_granite1",
    "enc_dragon_granite2",
    "enc_mouse_cadet0",
    "enc_mouse_cadet1",
    "enc_mouse_cadet2",
    "enc_frog_tinkerer0",
    "enc_frog_tinkerer1",
    "enc_frog_tinkerer2",
    "enc_bird_student0",
    "enc_bird_student1",
    "enc_bird_whispering0",
    "enc_bird_whispering1",
    "enc_bird_archon0",
    "enc_bird_valedictorian0",
    "enc_bird_valedictorian1",
    "enc_wolf_greyeye0",
    "enc_wolf_greyeye1",
    "enc_wolf_bluepaw0",
    "enc_wolf_bluepaw1",
    "enc_wolf_snowfur0",
    "enc_wolf_steeltooth0",
    "enc_wolf_steeltooth1",
    "enc_dragon_gold0",
    "enc_dragon_gold1",
    "enc_dragon_emerald0",
    "enc_dragon_emerald1",
    "enc_dragon_ruby0",
    "enc_dragon_mythril0",
    "enc_dragon_mythril1",
    "enc_mouse_archer0",
    "enc_mouse_archer1",
    "enc_mouse_oakspear0",
    "enc_mouse_oakspear1",
    "enc_mouse_rosemage0",
    "enc_mouse_paladin0",
    "enc_mouse_paladin1",
    "enc_frog_seamstress0",
    "enc_frog_seamstress1",
    "enc_frog_songstress0",
    "enc_frog_songstress1",
    "enc_frog_painter0",
    "enc_frog_idol0",
    "enc_frog_idol1",
    "enc_queens_staff0",
    "enc_queens_knife0",
    "enc_queens_axe0",
    "enc_queens_spear0",
    "enc_queens_harp0",
    "enc_rabbit_queen0",
    "enc_rabbit_queen1",
    "enc_geode_moth0",
    "enc_geode_moth1",
    "enc_geode_moth2",
    "enc_geode_firefly0",
    "enc_geode_firefly1",
    "enc_geode_firefly2",
    "enc_geode_butterfly0",
    "enc_geode_butterfly1",
    "enc_geode_butterfly2",
    "enc_depths_basilisk0",
    "enc_depths_basilisk1",
    "enc_depths_beast0",
    "enc_depths_beast1",
    "enc_depths_angel0",
    "enc_depths_hound0",
    "enc_depths_hound1",
    "enc_sanct_saph0",
    "enc_sanct_saph1",
    "enc_sanct_capricorn0",
    "enc_sanct_capricorn1",
    "enc_sanct_flower0",
    "enc_sanct_owl0",
    "enc_sanct_owl1",
    "enc_aurum_whitecat0",
    "enc_aurum_whitecat1",
    "enc_aurum_beast0",
    "enc_aurum_beast1",
    "enc_aurum_ghost0",
    "enc_aurum_blackcat0",
    "enc_aurum_blackcat1",
    "enc_darkhall_spelllock0",
    "enc_darkhall_spelllock1",
    "enc_darkhall_spelllock2",
    "enc_darkhall_spelllock3",
    "enc_darkhall_spelllock4",
    "enc_heart_witch0",
    "enc_heart_witch1",
    "enc_toybox_sphere",
    "enc_toybox_sphere_attack",
    "enc_toybox_sphere_move",
];

// Based on scr_stagefirst_get_name
// const STAGE_NAMES: [(&'static str, &'static str); 16] = [
//     ("stg_random_base", "Random (Kingdom)"),
//     // ("stg_outskirts", "Kingdom Outskirts"),
//     ("stg_nest", "Scholar's Nest"),
//     ("stg_arsenal", "King's Arsenal"),
//     ("stg_lighthouse", "Red Darkhouse"),
//     ("stg_streets", "Churchmouse Streets"),
//     ("stg_lakeside", "Emerald Lakeside"),
//     // ("stg_geode", "Crack in the Geode"),
//     ("stg_depths", "Darkhouse Depths"),
//     ("stg_sanct", "Subterra Sanctum"),
//     ("stg_aurum", "Atelier Aurum"),
//     // ("stg_darkhall", "Looping Hallway"),
//     // ("stg_reflection", "Reflecting Pool"),
//     // ("stg_keep", "The Pale Keep"),
//     // ("stg_pinnacle", "Moonlit Pinnacle"),
//     ("stg_random_dlc", "Random (Extra)"),
//     ("stg_random_true", "True Random"),
//     ("stg_random_chaos", "Chaotic Random"),
//     ("stg_random", "Random Route"),
//     ("stg_credits", "Credits"),
//     ("stg_credits_dlc", "Credits (Extra)"),
//     ("stg_random", "Random Route"),
// ];
